/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsInt } from "class-validator";
import { ContractTypeWhereUniqueInput } from "../../contractType/base/ContractTypeWhereUniqueInput";
import { Type } from "class-transformer";
import { NftUpdateManyWithoutContractsInput } from "./NftUpdateManyWithoutContractsInput";
@InputType()
class ContractUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string;

  @ApiProperty({
    required: false,
    type: () => ContractTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ContractTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => ContractTypeWhereUniqueInput, {
    nullable: true,
  })
  contractType?: ContractTypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  externalLink?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  feeRecipient?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NftUpdateManyWithoutContractsInput,
  })
  @ValidateNested()
  @Type(() => NftUpdateManyWithoutContractsInput)
  @IsOptional()
  @Field(() => NftUpdateManyWithoutContractsInput, {
    nullable: true,
  })
  nfts?: NftUpdateManyWithoutContractsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  sellerFeeBasisPoints?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  uri?: string | null;
}
export { ContractUpdateInput };
