/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { CollectionListRelationFilter } from "../../collection/base/CollectionListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { NftListRelationFilter } from "../../nft/base/NftListRelationFilter";
@InputType()
class ContractWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  address?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => CollectionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CollectionListRelationFilter)
  @IsOptional()
  @Field(() => CollectionListRelationFilter, {
    nullable: true,
  })
  collections?: CollectionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => NftListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NftListRelationFilter)
  @IsOptional()
  @Field(() => NftListRelationFilter, {
    nullable: true,
  })
  nfts?: NftListRelationFilter;
}
export { ContractWhereInput };
