/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMetadatumArgs } from "./CreateMetadatumArgs";
import { UpdateMetadatumArgs } from "./UpdateMetadatumArgs";
import { DeleteMetadatumArgs } from "./DeleteMetadatumArgs";
import { MetadatumFindManyArgs } from "./MetadatumFindManyArgs";
import { MetadatumFindUniqueArgs } from "./MetadatumFindUniqueArgs";
import { Metadatum } from "./Metadatum";
import { AttributeFindManyArgs } from "../../attribute/base/AttributeFindManyArgs";
import { Attribute } from "../../attribute/base/Attribute";
import { NftFindManyArgs } from "../../nft/base/NftFindManyArgs";
import { Nft } from "../../nft/base/Nft";
import { MetadatumService } from "../metadatum.service";

@graphql.Resolver(() => Metadatum)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class MetadatumResolverBase {
  constructor(
    protected readonly service: MetadatumService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "read",
    possession: "any",
  })
  async _metadataMeta(
    @graphql.Args() args: MetadatumFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Metadatum])
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "read",
    possession: "any",
  })
  async metadata(
    @graphql.Args() args: MetadatumFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Metadatum[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Metadatum",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Metadatum, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "read",
    possession: "own",
  })
  async metadatum(
    @graphql.Args() args: MetadatumFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Metadatum | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Metadatum",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Metadatum)
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "create",
    possession: "any",
  })
  async createMetadatum(
    @graphql.Args() args: CreateMetadatumArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Metadatum> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Metadatum",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Metadatum"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Metadatum)
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "update",
    possession: "any",
  })
  async updateMetadatum(
    @graphql.Args() args: UpdateMetadatumArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Metadatum | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Metadatum",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Metadatum"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Metadatum)
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "delete",
    possession: "any",
  })
  async deleteMetadatum(
    @graphql.Args() args: DeleteMetadatumArgs
  ): Promise<Metadatum | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Attribute])
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "read",
    possession: "any",
  })
  async attributes(
    @graphql.Parent() parent: Metadatum,
    @graphql.Args() args: AttributeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attribute[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Attribute",
    });
    const results = await this.service.findAttributes(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Nft])
  @nestAccessControl.UseRoles({
    resource: "Metadatum",
    action: "read",
    possession: "any",
  })
  async nfts(
    @graphql.Parent() parent: Metadatum,
    @graphql.Args() args: NftFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Nft[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Nft",
    });
    const results = await this.service.findNfts(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
