/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { AttributeCreateNestedManyWithoutMetadataInput } from "./AttributeCreateNestedManyWithoutMetadataInput";
import { Type } from "class-transformer";
import { NftCreateNestedManyWithoutMetadataInput } from "./NftCreateNestedManyWithoutMetadataInput";
@InputType()
class MetadatumCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  animationUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => AttributeCreateNestedManyWithoutMetadataInput,
  })
  @ValidateNested()
  @Type(() => AttributeCreateNestedManyWithoutMetadataInput)
  @IsOptional()
  @Field(() => AttributeCreateNestedManyWithoutMetadataInput, {
    nullable: true,
  })
  attributes?: AttributeCreateNestedManyWithoutMetadataInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  backgroundColor?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  externalUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NftCreateNestedManyWithoutMetadataInput,
  })
  @ValidateNested()
  @Type(() => NftCreateNestedManyWithoutMetadataInput)
  @IsOptional()
  @Field(() => NftCreateNestedManyWithoutMetadataInput, {
    nullable: true,
  })
  nfts?: NftCreateNestedManyWithoutMetadataInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  youTubeUrl?: string | null;
}
export { MetadatumCreateInput };
