/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { AttributeUpdateManyWithoutMetadataInput } from "./AttributeUpdateManyWithoutMetadataInput";
import { Type } from "class-transformer";
import { NftUpdateManyWithoutMetadataInput } from "./NftUpdateManyWithoutMetadataInput";
@InputType()
class MetadatumUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  animationUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => AttributeUpdateManyWithoutMetadataInput,
  })
  @ValidateNested()
  @Type(() => AttributeUpdateManyWithoutMetadataInput)
  @IsOptional()
  @Field(() => AttributeUpdateManyWithoutMetadataInput, {
    nullable: true,
  })
  attributes?: AttributeUpdateManyWithoutMetadataInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  backgroundColor?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  externalUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NftUpdateManyWithoutMetadataInput,
  })
  @ValidateNested()
  @Type(() => NftUpdateManyWithoutMetadataInput)
  @IsOptional()
  @Field(() => NftUpdateManyWithoutMetadataInput, {
    nullable: true,
  })
  nfts?: NftUpdateManyWithoutMetadataInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  youTubeUrl?: string | null;
}
export { MetadatumUpdateInput };
