/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateContractTypeArgs } from "./CreateContractTypeArgs";
import { UpdateContractTypeArgs } from "./UpdateContractTypeArgs";
import { DeleteContractTypeArgs } from "./DeleteContractTypeArgs";
import { ContractTypeFindManyArgs } from "./ContractTypeFindManyArgs";
import { ContractTypeFindUniqueArgs } from "./ContractTypeFindUniqueArgs";
import { ContractType } from "./ContractType";
import { ContractTypeService } from "../contractType.service";

@graphql.Resolver(() => ContractType)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ContractTypeResolverBase {
  constructor(
    protected readonly service: ContractTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ContractType",
    action: "read",
    possession: "any",
  })
  async _contractTypesMeta(
    @graphql.Args() args: ContractTypeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ContractType])
  @nestAccessControl.UseRoles({
    resource: "ContractType",
    action: "read",
    possession: "any",
  })
  async contractTypes(
    @graphql.Args() args: ContractTypeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContractType[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ContractType",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ContractType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ContractType",
    action: "read",
    possession: "own",
  })
  async contractType(
    @graphql.Args() args: ContractTypeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContractType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ContractType",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ContractType)
  @nestAccessControl.UseRoles({
    resource: "ContractType",
    action: "create",
    possession: "any",
  })
  async createContractType(
    @graphql.Args() args: CreateContractTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContractType> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ContractType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ContractType"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ContractType)
  @nestAccessControl.UseRoles({
    resource: "ContractType",
    action: "update",
    possession: "any",
  })
  async updateContractType(
    @graphql.Args() args: UpdateContractTypeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ContractType | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ContractType",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ContractType"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ContractType)
  @nestAccessControl.UseRoles({
    resource: "ContractType",
    action: "delete",
    possession: "any",
  })
  async deleteContractType(
    @graphql.Args() args: DeleteContractTypeArgs
  ): Promise<ContractType | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
